### PR TITLE
Added fix for potential radius

### LINKED ISSUE #483: "potientialRadius" must be set in the Network API
The ```potentialRadius``` is a "derived" value that is set to the ```inputWidth``` within NuPIC's OPF & Network API (see [NuPIC Issue 3366](https://github.com/numenta/nupic/issues/3366)) - and has a large effect on the performance of the system. The same thing must be done within HTM.Java's NAPI so that the configuration is correct.

This must be done prior to the new release!

### PR DESCRIPTION
**Pull request by cogmission**
Fixes #483

### CODE REVIEW

**Comment by cogmission** [comment]
@rhyolight Please accept. This is the potentialRadius fix for HTM.Java

File: src/main/java/org/numenta/nupic/Connections.java [hunk 1]
```diff
@@ -489,11 +515,16 @@ public void setPotentialRadius(int potentialRadius) {
 
     /**
      * Returns the configured potential radius
+     * 
+     * <b>WARNING:</b> potentialRadius **must** be set to 
+     * the inputWidth if using "globalInhibition" and if not 
+     * using the Network API (which sets this automatically) 
+     *
```
Comment (rhyolight) [inline src/main/java/org/numenta/nupic/Connections.java]: No need for this warning comment on a getter.

File: src/main/java/org/numenta/nupic/Parameters.java [hunk 2]
```diff
@@ -97,7 +97,11 @@
         //////////// Spatial Pooler Parameters ///////////
         Map<KEY, Object> defaultSpatialParams = new ParametersMap();
         defaultSpatialParams.put(KEY.INPUT_DIMENSIONS, new int[]{64});
-        defaultSpatialParams.put(KEY.POTENTIAL_RADIUS, 16);
+        /** <b>WARNING:</b> potentialRadius **must** be set to 
+         * the inputWidth if using "globalInhibition" and if not 
+         * using the Network API (which sets this automatically) 
+         */
+        defaultSpatialParams.put(KEY.POTENTIAL_RADIUS, -1);
```
Comment (rhyolight) [inline src/main/java/org/numenta/nupic/Parameters.java]: I think this warning is in too many places. It makes sense to put it in the setter or constructor (where the value can be set), but not everywhere.

Comment (cogmission) [inline src/main/java/org/numenta/nupic/Parameters.java]: I removed this one, but I added it (where it should have been), on the key itself (where it will be looked up).

File: src/main/java/org/numenta/nupic/Connections.java (hunk 1 above)
Comment (cogmission) [inline src/main/java/org/numenta/nupic/Connections.java]: Ok. I removed this one on the "getter"
