### PR TITLE
0.6.2 snapshot release

### LINKED ISSUE #292: Port ExtensiveTemporalMemoryTest H10 changes
modify this test to include the fixes for the Python version

### LINKED ISSUE #305: Synapse.destroy() doesn't remove reference from Connections.
Upon destroy() method being called, the Connections class still holds the Synapse inside the owning segment's mapped list of Synapses. (Remove method is not working due to querky equals method).

### LINKED ISSUE #306: NetworkTest: testBasicNetwork() method's name doesn't describe actions of test.
The testBasicNetwork() method really tests the halt() and onComplete() functions are working. This should be split into two tests; one that tests the halt() and onComplete(), and one that tests halt() and onComplete() after running for at least 1000 iterations (since running 100 iterations revealed a bug) see
#305

### LINKED ISSUE #308: NAPI needs ability to set "isLearn" externally
"isLearn" can right now be set from within the input stream as designated by the header, however it cannot be set as a parameter externally - we should have this ability.

### PR DESCRIPTION
**Pull request by cogmission**
Fixes #292 
Fixes #305 
Fixes #306 
Fixes #308

### CODE REVIEW

**Comment by cogmission** [comment]
@rhyolight

**Comment by cogmission** [comment]
@rhyolight Ok, added enough tests so that coverage increased... as seen [here](https://coveralls.io/builds/3574712/source?filename=src%2Fmain%2Fjava%2Forg%2Fnumenta%2Fnupic%2Falgorithms%2FSample.java)

please accept...

**Comment by cogmission** [comment]
@rhyolight this is actually ok, github is not updated with the coveralls status for some reason?

File: src/main/java/org/numenta/nupic/network/Layer.java [hunk 1]
```diff
@@ -1832,7 +1850,7 @@ public ManualInput call(ManualInput t1) {
                         
                         CLAClassifier c = (CLAClassifier)t1.getClassifiers().get(key);
                         ClassifierResult<Object> result = c.compute(
-                            recordNum, inputMap, t1.getSDR(), true, true);
+                            recordNum, inputMap, t1.getSDR(), isLearn, true);
```
Comment (antidata) [inline src/main/java/org/numenta/nupic/network/Layer.java]: I like this! Question @cogmission, would it be useful to get rid of `infer` hardcoding like you did with `isLearn` ?

Comment (cogmission) [inline src/main/java/org/numenta/nupic/network/Layer.java]: @antidata Thank you for bringing this up! Can you write this to the Hackers
ML ? I would like to discuss this openly because I'm wondering why "infer"
even exists?

On Tue, Sep 15, 2015 at 12:05 PM, antidata <notifications@github.com> wrote:

> In src/main/java/org/numenta/nupic/network/Layer.java
> <https://github.com/numenta/htm.java/pull/307#discussion_r39536419>:
>
> > @@ -1832,7 +1850,7 @@ public ManualInput call(ManualInput t1) {
> >
> >                          CLAClassifier c = (CLAClassifier)t1.getClassifiers().get(key);
> >                          ClassifierResult<Object> result = c.compute(
> > -                            recordNum, inputMap, t1.getSDR(), true, true);
> > +                            recordNum, inputMap, t1.getSDR(), isLearn, true);
>
> I like this! Question @cogmission <https://github.com/cogmission>, would
> it be useful to get rid of infer hardcoding like you did with isLearn ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/numenta/htm.java/pull/307/files#r39536419>.
>



-- 
*With kind regards,*

David Ray
Java Solutions Architect

*Cortical.io <http://cortical.io/>*
Sponsor of:  HTM.java <https://github.com/numenta/htm.java>

d.ray@cortical.io
http://cortical.io

**Comment by cogmission** [comment]
Muchas Gracias @rhyolight :+1:

File: src/main/java/org/numenta/nupic/network/Layer.java (hunk 1 above)
Comment (antidata) [inline src/main/java/org/numenta/nupic/network/Layer.java]: np, will send it later, thanks!
